import Descriptions from "@/components/Descriptions";
import Dog from "@/components/Dog";
import Parent from "@/components/Parent";
import User from "@/components/User";
import Welcome from "@/components/Welcome";
import Head from "next/head";

export default function Home() {
  return (
    // fragment: é semelhante a div, que seria um pai para os outros elesmentos dentro dela; entretanto, é uma boa prática usar <>
    <> 
      <Head>
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World!</h1>
        {/* Comentário em JSX */}
        {/* Chamando o componente */}
        <Welcome/>
        {/* Importando o componente User que possui uma expressão JSX */}
        <User/>
        {/* Componente pai que possui um componente filho incorporado */}
        <Parent/>
        {/* Chamando o componente e chamando as props*/}
        <Descriptions name="Giovana" age={19}/>
        {/* Chamando o componente e chamando as props - usando a desestruturação para passar props*/}
        <Dog name="Rex" breed="Pitbull"/>
      </main>
    </>
  );
}
