paths:
  /livros:
    get:
      summary: Retorna a lista de todos os livros cadastrados
      tags: [Livros]
      responses:
        200:
          description: Lista de livros
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "67ef10db697704ca79a093c5"
                    title:
                      type: string
                      example: "Demian"
                    author:
                      type: string
                      example: "Hermann Hesse"
                    year:
                      type: integer
                      example: 1919
                    details:
                      type: array
                      items:
                        type: object
                        properties:
                          genre:
                            type: string
                            example: "Fiction"
                          publisher:
                            type: string
                            example: "Fischer Verlag"
                          pages:
                            type: integer
                            example: 196
        500:
          description: Erro interno do servidor
    post:
      summary: Cadastra um novo livro
      tags: [Livros]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Demian"
                author:
                  type: string
                  example: "Hermann Hesse"
                year:
                  type: integer
                  example: 1919
                details:
                  type: array
                  items:
                    type: object
                    properties:
                      genre:
                        type: string
                        example: "Fiction"
                      publisher:
                        type: string
                        example: "Fischer Verlag"
                      pages:
                        type: integer
                        example: 196
      responses:
        201:
          description: Livro criado com sucesso
        400:
          description: Erro na requisição
        500:
          description: Erro interno do servidor
  /livros/{_id}:
    delete: 
      summary: Apagar registro de um livro
      tags: [Livros]
      parameters:
      - name: _id
        in: path
        description: ID do livro a ser excluído
        required: true
        schema:
          type: string
      responses:
        204:
          description: Livro excluído com sucesso
        400:
          description: Erro na requisição (ID inválido)
        404:
          description: Livro não encontrado
        500:
          description: Erro interno do servidor
    put:
      summary: Atualizar dados do livro
      tags: [Livros]
      parameters:
        - name: _id
          in: path
          description: ID do livro a ser excluído
          required: true
          schema:
            type: string
            example: "67ef10db697704ca79a093c5"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Demian"
                author:
                  type: string
                  example: "Hermann Hesse"
                year:
                  type: integer
                  example: 1919
                details:
                  type: array
                  items:
                    type: object
                    properties:
                      genre:
                        type: string
                        example: "Fiction"
                      publisher:
                        type: string
                        example: "Fischer Verlag"
                      pages:
                        type: integer
                        example: 196
      responses:
        200:
          description: Livro atualizado com sucesso
        400:
          description: Erro na requisição (ID inválido ou dados incorretos)
        404:
          description: Livro não encontrado
        500:
          description: Erro interno do servidor

    get:
      summary: Busca por um único livro
      tags: [Livros]
      parameters:
        - name: _id
          in: path
          description: ID do livro a ser retornado
          required: true
          schema:
            type: string
            example: "67ef10db697704ca79a093c5"
      responses:
        200:
          description: Livro encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: "67ef10db697704ca79a093c5"

                  title:
                    type: string
                    example: "Demian"
                  author:
                    type: string
                    example: "Hermann Hesse"
                  year:
                    type: integer
                    example: 1919
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        genre:
                          type: string
                          example: "Fiction"
                        publisher:
                          type: string
                          example: "Fischer Verlag"
                        pages:
                          type: integer
                          example: 196
        404:
          description: Livro não encontrado
        500:
          description: Erro interno do servidor

